### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'ip')

### ISSUE THREAD

**Issue by olalonde** [dickydoouk/tp-link-tapo-connect#28]
I'm getting this error when running the example:

```
> node src/index.js

TypeError: Cannot read properties of undefined (reading 'ip')
    at /Users/redacted/code/test/node_modules/tp-link-tapo-connect/dist/network-tools.js:51:118
    at step (/Users/redacted/code/test/node_modules/tp-link-tapo-connect/dist/network-tools.js:33:23)
    at Object.next (/Users/redacted/code/test/node_modules/tp-link-tapo-connect/dist/network-tools.js:14:53)
    at fulfilled (/Users/redacted/code/test/node_modules/tp-link-tapo-connect/dist/network-tools.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

```javascript
const devices = await listDevicesByType(cloudToken, 'SMART.TAPOPLUG');
    
    const smartPlug = devices[0];

    const deviceToken = await loginDevice(email, password, smartPlug);
    const getDeviceInfoResponse = await getDeviceInfo(deviceToken);
    console.log(getDeviceInfoResponse);
```

The device is on a remote network.

**Comment by BartaG512** [comment]
Getting the same error.

**Comment by ercksen** [comment]
Had the same issue and my problem was with ARP. I am using a WiFi to LAN Bridge in my case which is not transparent, so it was not able to find the correct MAC address. As no non-null assertion is made, you get this error.

Feedback could be better, but the actual problem probably has to do with your ARP setup. Are you running inside Docker?

**Comment by valinotti4** [comment]
Any workaround for this issue? I am also trying to run the script from an external network. If I run it from the same network as the smart plug is conected, it works fine.

Thanks!
