### ISSUE TITLE
Session Cookie is undefined when using loginDeviceByIp

### ISSUE THREAD

**Issue by josephdadams** [dickydoouk/tp-link-tapo-connect#44]
Hey there, I am getting this error when using `loginDeviceByIp`.

```
TypeError: Cannot read properties of undefined (reading '0')
    at /tp-link-tapo-connect/dist/klap-transport.js:82:65
    at step (/tp-link-tapo-connect/dist/klap-transport.js:48:23)
    at Object.next (/tp-link-tapo-connect/dist/klap-transport.js:29:53)
    at fulfilled (/tp-link-tapo-connect/dist/klap-transport.js:20:58)

```

 The response headers look like this and are missing the session-cookie header:

```javascript
{
  server: 'SHIP 2.0',
  'content-length': '49',
  'content-type': 'text/html'
}
```

Here is a sample device:
```javascript
{
    deviceType: 'SMART.TAPOPLUG',
    role: 0,
    fwVer: '1.1.5 Build 230324 Rel.143956',
    appServerUrl: 'https://aps1-wap.tplinkcloud.com',
    deviceRegion: 'ap-southeast-1',
    deviceId: '8022DB4B77982E9653FB72000AF2DBA220AD76B7',
    deviceName: 'P100',
    deviceHwVer: '2.0',
    alias: '5 Aux LX Powerboard',
    deviceMac: '30DE4B81A391',
    oemId: 'E5BB4AABA271989E08B53330464D4144',
    deviceModel: 'P100(AU)',
    hwId: '7B605B6C691A174AEFBB7135F1C22659',
    fwId: '00000000000000000000000000000000',
    isSameRegion: false,
    status: 0
  }
```

Any thoughts? I will say that this plug is the AU (Australia) version - I am not seeing this error on a US version.

We are using this repository in this downstream project: https://github.com/bitfocus/companion-module-tplink-taposmartplug

**Comment by josephdadams** [comment]
@doogiechap this is the issue we are having with your plug.
