### ISSUE TITLE
error TypeError: Passphrase required for encrypted key

### ISSUE THREAD

**Issue by bigandy** [dickydoouk/tp-link-tapo-connect#5]
Getting the following error on v1.0.2

error TypeError: Passphrase required for encrypted key
    at Object.privateDecrypt (internal/crypto/cipher.js:61:12)
    at Object.readDeviceKey (/Users/andrew/Sites/house-control/node_modules/tp-link-tapo-connect/dist/tplinkCipher.js:82:38)
    at /Users/andrew/Sites/house-control/node_modules/tp-link-tapo-connect/dist/api.js:143:44
    at step (/Users/andrew/Sites/house-control/node_modules/tp-link-tapo-connect/dist/api.js:44:23)
    at Object.next (/Users/andrew/Sites/house-control/node_modules/tp-link-tapo-connect/dist/api.js:25:53)
    at fulfilled (/Users/andrew/Sites/house-control/node_modules/tp-link-tapo-connect/dist/api.js:16:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_MISSING_PASSPHRASE'
}

**Comment by bigandy** [comment]
so after looking at the code in the node_modules/tp-link-tapo-connect/dist/tplinkCipher.js it is not the same as when I do a `npm run build` in this repo. Should be resolved by doing a build and re-publishing.

**Comment by dickydoouk** [comment]
Sorry I have not been able to replicate this issue. I have verified that the published version 1.0.2 contains the latest passphrase fix. Did you update `package.json` lib and run `npm install` as that upgraded it in my test app for me. Failing that deleting `node_modules` and then run `npm install`.

**Comment by dickydoouk** [comment]
Sorry I s

**Comment by bigandy** [comment]
thanks!
